server:
  port: 8080
log:
  level: info
database:
  host: localhost
  port: 3306
  username: root
  password: root
  database: super_db
  charset: utf8mb4
  timezone: UTC
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 10s
  logLevel: silent
  parseTime: true
redis:
  host: localhost
  port: 6379
  password: root
  db: 0
